// Temperature constants for different AI model providers
export const ANTHROPIC_DEFAULT_TEMPERATURE = 0
export const BEDROCK_DEFAULT_TEMPERATURE = 0.3
export const DEEP_SEEK_DEFAULT_TEMPERATURE = 0.6
export const GEMINI_DEFAULT_TEMPERATURE = 0
export const GLAMA_DEFAULT_TEMPERATURE = 0
export const LMSTUDIO_DEFAULT_TEMPERATURE = 0
export const MISTRAL_DEFAULT_TEMPERATURE = 0
export const OLLAMA_DEFAULT_TEMPERATURE = 0
export const OPENAI_NATIVE_DEFAULT_TEMPERATURE = 0
export const OPENAI_DEFAULT_TEMPERATURE = 0
export const OPENROUTER_DEFAULT_TEMPERATURE = 0
export const UNBOUND_DEFAULT_TEMPERATURE = 0
export const VERTEX_DEFAULT_TEMPERATURE = 0
