title: CoolCline Documentation
description: Documentation for the CoolCline project
remote_theme: just-the-docs/just-the-docs

url: https://docs.coolcline.com

aux_links:
  "CoolCline on GitHub":
    - "//github.com/CoolCline/CoolCline"

# Enable search
search_enabled: true

# Enable dark mode
color_scheme: dark
